{% set name = "h5pulsar" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/h5pulsar-{{ version }}.tar.gz
  sha256: e1cead43f86abda1b4696799900bb9a9b7146c0cc48d3f4e6aa86adc01b03d9d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip >=23.1.2
  run:
    - python >=3.9
    - astropy-base >=5.3
    - enterprise-pulsar >=3.3.2
    - h5py >=3.8.0
    - libstempo >=2.4.5
    - numpy >=1.24.3
    - packaging >=23.1
    - pint-pulsar >=0.9.5
    - ephem >=4.1.4

test:
  imports:
    - h5pulsar

about:
  home: https://pypi.org/project/h5pulsar/
  summary: HDF5 files for Pulsar timing data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AaronDJohnson
